---
apiVersion: microgateway.airlock.com/v1alpha1
kind: HeaderRewrites
metadata:
  name: header-rewrites-nextcloud
  namespace: nextcloud
spec:
  settings:
    operationalMode: Production
  request:
    allow:
      matchingHeaders:
        builtIn:
          standardHeaders: true
        custom:
          - name: Allow CSRF-Token header
            headers:
              - name:
                  matcher:
                    exact: requesttoken
    remove:
      builtIn:
        alternativeForwardedHeaders: true
    add: {}
  response:
    allow:
      allHeaders: {}
    remove:
      builtIn:
        informationLeakage:
          server: true
          application: true
        auth:
          basic: false
          ntlm: true
          negotiate: true
        permissiveCors: true
    add:
      builtIn:
        xFrameOptions: true
        hsts: true
        hstsPreload: false
        csp: true
        xContentTypeOptions: true
        referrerPolicy: true
        featurePolicy: true
