apiVersion: microgateway.airlock.com/v1alpha1
kind: SidecarGateway
metadata:
  name: sidecar-gateway-nextcloud
  namespace: nextcloud
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: nextcloud
      app.kubernetes.io/name: nextcloud
  applications:
  - containerPort: 80 # Port of the to be protected container
    routes:
    - pathPrefix: /
      secured:
        contentSecurityRef:
          name: content-security-nextcloud # contentSecurity.yaml
