apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loki-servicemonitor-access
  namespace: monitoring
rules:
- apiGroups: [ "monitoring.coreos.com" ]
  resources: [ "servicemonitors" ]
  verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loki-servicemonitor-access-binding
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: loki-servicemonitor-access
subjects:
- kind: ServiceAccount
  name: loki-helm-operator-controller-manager
  namespace: monitoring
