apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmCharts:
- name: alloy
  repo: https://grafana.github.io/helm-charts
  version: 1.4.0
  releaseName: alloy
  valuesFile: values.yaml
