---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis

resources:
- namespace.yaml
- redis-cert

helmCharts:
- name: redis
  releaseName: redis
  namespace: redis
  repo: oci://registry-1.docker.io/bitnamicharts
  version: 20.13.4
  valuesFile: values.yaml
