apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: cluster-ca
  secretName: cluster-ca-key-pair
  duration: 87600h # 10 years
  renewBefore: 720h # renew 30 days before expiration
  issuerRef:
    name: cluster-ca-selfsigned
    kind: ClusterIssuer
