---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

helmCharts:
- name: microgateway
  releaseName: airlock-microgateway
  namespace: airlock-microgateway-system
  repo: oci://quay.io/airlockcharts
  version: 4.7.2
  valuesFile: microgateway-values.yaml
  includeCRDs: true
