apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmCharts:
- name: alloy
  repo: https://grafana.github.io/helm-charts
  version: 0.12.6 # or the latest Alloy version
  releaseName: alloy
  valuesFile: values.yaml
