---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmCharts:
  - name: loki
    releaseName: loki
    namespace: monitoring
    repo: https://grafana.github.io/helm-charts
    version: 6.45.2
    includeCRDs: true
    valuesFile: values.yaml
