---
## Install the Single Binary Helm Chart
## https://grafana.com/docs/loki/latest/installation/helm/install-monolithic/#install-the-single-binary-helm-chart
deploymentMode: SingleBinary

test:
  enabled: false

monitoring:
  serviceMonitor:
    enabled: true
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  schemaConfig:
    configs:
    - from: "2024-01-01"
      store: tsdb
      index:
        prefix: loki_index_
        period: 24h
      object_store: filesystem
      schema: v13
singleBinary:
  replicas: 1
read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0
chunksCache:
  # default is 500MB, with limited memory keep this smaller
  writebackSizeLimit: 10MB
  allocatedMemory: 256
