controller:
  type: deployment
  replicas: 1

alloy:
  configMap:
    create: true
    content: |
      // Discover all pods
      discovery.kubernetes "pod" {
        role = "pod"
      }

      // Filter down to Airlock Microgateway logs only
      discovery.relabel "airlock_pod_logs" {
        targets = discovery.kubernetes.pod.targets

        // Keep only the airlock-gateway namespace
        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          regex         = "airlock-gateway"
          action        = "keep"
        }

        // Keep only the two containers we care about
        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          regex         = "airlock-microgateway-engine|airlock-microgateway-session-agent"
          action        = "keep"
        }

        // Friendly labels for querying
        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          target_label  = "namespace"
          action        = "replace"
        }
        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          target_label  = "pod"
          action        = "replace"
        }
        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          target_label  = "container"
          action        = "replace"
        }

        // Static service label to simplify LogQL
        rule {
          target_label  = "service"
          replacement   = "airlock-microgateway"
          action        = "replace"
        }
      }

      // Tail via Kubernetes API (no hostPath mounts)
      loki.source.kubernetes "pods" {
        targets    = discovery.relabel.airlock_pod_logs.output
        forward_to = [loki.process.airlock.receiver]
      }

      // Add cluster/service labels and forward to Loki
      loki.process "airlock" {
        stage.static_labels {
          values = {
            cluster = "my-cluster",
            service = "airlock-microgateway",
          }
        }
        forward_to = [loki.write.default.receiver]
      }

      // Push to Loki (tenant set explicitly; change if needed)
      loki.write "default" {
        endpoint {
          url       = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
          tenant_id = "fake"
        }
      }

#resources:
#  requests:
#    cpu: 100m
#    memory: 128Mi
#  limits:
#    cpu: 200m
#    memory: 256Mi
