---
operator:
  gatewayAPI:
    enabled: true
    podMonitor:
      create: true
      labels:
        release: "kube-prometheus-stack"
  serviceMonitor:
    create: true
    labels:
      release: "kube-prometheus-stack"
engine:
  sidecar:
    podMonitor:
      create: true
      labels:
        release: "kube-prometheus-stack"
dashboards:
  create: true
