---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud

resources:
  - namespace.yaml

helmCharts:
  - name: nextcloud
    releaseName: nextcloud
    namespace: nextcloud
    repo: https://nextcloud.github.io/helm/
    version: 8.5.0
    valuesFile: values.yaml
