---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sessionstore
- gateway-tls-cert.yaml
- gateway.yaml
- gatewayclass.yaml # Not needed with Microgateway 4.7+
- gatewayparameters.yaml
- namespace.yaml
- servicemonitor.yaml
