apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-certificate
  namespace: redis
spec:
  dnsNames:
  - redis-master.redis.svc.cluster.local

  privateKey:
    size: 4096

  usages:
  - client auth
  - server auth

  commonName: redis-master.redis.svc.cluster.local

  issuerRef:
    kind: ClusterIssuer
    name: cluster-ca-issuer

  secretName: redis-certificate
