securityContext:
  runAsUser: null
  fsGroup: null
  runAsGroup: null

podSecurityContext:
  enabled: false

testFramework:
  enabled: false

ingress:
  enabled: true
  path: /
  hosts:
  - grafana-127-0-0-1.nip.io
  targetPort: 3000

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    searchNamespace: ALL
    folderAnnotation: grafana_folder
    provider:
      foldersFromFilesStructure: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: loki
      type: loki
      url: http://loki-gateway/
      access: proxy
      version: 1
      isDefault: true
      jsonData:
        maxLines: 1000
    - name: Prometheus
      type: prometheus
      access: proxy
      url: https://thanos-querier.openshift-monitoring.svc:9091
      isDefault: false
      jsonData:
        tlsSkipVerify: true
        httpHeaderName1: "Authorization"
      secureJsonData:
        httpHeaderValue1: "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlhUa09Lek5IUzNoY2s3eDkxNDF0WV92Nlp4RDZBenVwTTk5MHdrM21vNlEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MjA2OTgzNzA3MywiaWF0IjoxNzU0NDc3MDczLCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJqdGkiOiI0NjdmMDI4OS1lNjgyLTQ0YmYtYjBiMC05NWJhMzU5N2I2YWYiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6Im1vbml0b3JpbmciLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZ3JhZmFuYSIsInVpZCI6IjE3ZGE3MmI4LTU3NmItNGJhNi1iZDEyLTRmNDUyMDJjMTg3OCJ9fSwibmJmIjoxNzU0NDc3MDczLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6bW9uaXRvcmluZzpncmFmYW5hIn0.oHNzOCPZwR13lhxgvOyoVUyOQVAo3LjrI8SG51tBITM_dQQ-WmWT8jiiDT4prrEH2Z0_ylyZq4CyV7sia9lIes5jPieEXELUAm3lM2jquohNyORxXZvGLvk6jjXlQ9HJCSWbMoa_Fg5-X5jO-GNogNvOJxQgf7BotQfbZTI6znZZdJyq_KGZNpa-sOJAm5tdMtHE08u-BzFLmKVX_-1mWmRSFM69RwxS_ejDAHTFEwdULe0ERwblWVbVBWPMzjv5BT_g1VtB9ahCMYHikE6YQDqnf7rHiVotTtM0CFYH5e8a8Mobx2CbSJBhxoX5Kbbp2oyQwyAfY1U3Lgx4WAWCNoLzDP8xrYSWRo01u8QoC6AKYy2UDujMV4bGcbT7BI9hvMUypmsSz9W8IIWUcsFTvmySHjrTNybP7tSPGIyneINML_t9f6dGgwSUmcuu5-m4WulypL6tzX300lAAFfYwLCc8MwmB-F-6IbfSC6W6jV2g-6R87wDDHbFoP6mcLecQt4H0Uheaedr8ar1T4uTtB68o7SR3tQWXPCpaVu8IzFH5Mq3CJBgaF4vnXMXVjjNFyfP0BHNAxcM4Fwndd2idlfhVSyH5AHiFfVAACwjhO_Zs6A8lT1rAGDhLirIcOPzMIBUHhYl-MlPKGZfLZzYbJC0e9hJqc2q0D4TH05yWE00"

env:
  GF_AUTH_ANONYMOUS_ENABLED: true
  GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
  GF_USERS_DEFAULT_THEME: light
