securityContext:
  runAsUser: null
  fsGroup: null
  runAsGroup: null

podSecurityContext:
  enabled: false

testFramework:
  enabled: false

ingress:
  enabled: true
  path: /
  hosts:
  - grafana-127-0-0-1.nip.io
  targetPort: 3000

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    searchNamespace: ALL
    folderAnnotation: grafana_folder
    provider:
      foldersFromFilesStructure: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: loki
      type: loki
      url: https://logging-loki-gateway-http.monitoring.svc:8080/api/logs/v1/application
      access: proxy
      jsonData:
        tlsSkipVerify: true
        httpHeaderName1: "Authorization"
      secureJsonData:
        httpHeaderValue1: "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlhUa09Lek5IUzNoY2s3eDkxNDF0WV92Nlp4RDZBenVwTTk5MHdrM21vNlEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MjA3MDAyNTc1MSwiaWF0IjoxNzU0NjY1NzUxLCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJqdGkiOiIzYmMzMjJjZi02OGM2LTRmYmQtOGVhZS01ZjQ1Mzg5Y2UwZWYiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6Im1vbml0b3JpbmciLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZ3JhZmFuYSIsInVpZCI6IjE3ZGE3MmI4LTU3NmItNGJhNi1iZDEyLTRmNDUyMDJjMTg3OCJ9fSwibmJmIjoxNzU0NjY1NzUxLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6bW9uaXRvcmluZzpncmFmYW5hIn0.KrkZRy_9Io9fWeJuyf9eQ4egleG0qSVe-N3O25W5jsju7bW5oxVA0giwTQywngcvbdGtA9M295gmQA_AGur_xag6gutJRf9JDJfxqc9-BQF8pe2sacB2yV7jw8EHMUrT88iTt88Cl0KNKFwbCnvYeg_7vosH39Knww0LBcuV06evNGuJMjslRe9Bt6jz8syk55SZDshSJLsueIwYyMRg2GqMJhpR1U50NzeZNBv8lYKaYoBuBBUksDinXHa8iJ2CGDw-ZoWUmeAHg6APPvs50kGWbuNnPvM5FrQHRg1A1sxpFfHmT3m2TuOVIT1QkG80RLbyKih5qsciFRW7i1O0FEtKtZvQ_WJR07j6ILwGMatvBTI_-SNIomslfNH4f-Zzq9VjhZljV0W-5Hpe0SUaLqIpqg7GXhJhhhM_8BsQ9R_Ck3Vsgoy0vMoErfjqM6qdtj_6MLNyvvjtS949Aibfe4BVIULLLo4VdZBmThKr1k6_1fBvlkzJYGzH_2i1vztDzfsB9DEkCm5i7U9oOMcItMVG-qqBYfYiBM5gjkWamoE0rzGuocXdvaePIf2GlTS--s3zsZpdriuV-r7-C444MND-xNj3bbd_7oq5BWZ2pHHa2wap1fPg3wXQUrtIjCNLNsFy23fzFot6rqFERzsiEXAEdrVaW3qO5gLa_tZdAhs"
    - name: Prometheus
      type: prometheus
      access: proxy
      url: https://thanos-querier.openshift-monitoring.svc:9091
      isDefault: false
      jsonData:
        tlsSkipVerify: true
        httpHeaderName1: "Authorization"
      secureJsonData:
        httpHeaderValue1: "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlhUa09Lek5IUzNoY2s3eDkxNDF0WV92Nlp4RDZBenVwTTk5MHdrM21vNlEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MjA3MDAyNTc1MSwiaWF0IjoxNzU0NjY1NzUxLCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJqdGkiOiIzYmMzMjJjZi02OGM2LTRmYmQtOGVhZS01ZjQ1Mzg5Y2UwZWYiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6Im1vbml0b3JpbmciLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZ3JhZmFuYSIsInVpZCI6IjE3ZGE3MmI4LTU3NmItNGJhNi1iZDEyLTRmNDUyMDJjMTg3OCJ9fSwibmJmIjoxNzU0NjY1NzUxLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6bW9uaXRvcmluZzpncmFmYW5hIn0.KrkZRy_9Io9fWeJuyf9eQ4egleG0qSVe-N3O25W5jsju7bW5oxVA0giwTQywngcvbdGtA9M295gmQA_AGur_xag6gutJRf9JDJfxqc9-BQF8pe2sacB2yV7jw8EHMUrT88iTt88Cl0KNKFwbCnvYeg_7vosH39Knww0LBcuV06evNGuJMjslRe9Bt6jz8syk55SZDshSJLsueIwYyMRg2GqMJhpR1U50NzeZNBv8lYKaYoBuBBUksDinXHa8iJ2CGDw-ZoWUmeAHg6APPvs50kGWbuNnPvM5FrQHRg1A1sxpFfHmT3m2TuOVIT1QkG80RLbyKih5qsciFRW7i1O0FEtKtZvQ_WJR07j6ILwGMatvBTI_-SNIomslfNH4f-Zzq9VjhZljV0W-5Hpe0SUaLqIpqg7GXhJhhhM_8BsQ9R_Ck3Vsgoy0vMoErfjqM6qdtj_6MLNyvvjtS949Aibfe4BVIULLLo4VdZBmThKr1k6_1fBvlkzJYGzH_2i1vztDzfsB9DEkCm5i7U9oOMcItMVG-qqBYfYiBM5gjkWamoE0rzGuocXdvaePIf2GlTS--s3zsZpdriuV-r7-C444MND-xNj3bbd_7oq5BWZ2pHHa2wap1fPg3wXQUrtIjCNLNsFy23fzFot6rqFERzsiEXAEdrVaW3qO5gLa_tZdAhs"

env:
  GF_AUTH_ANONYMOUS_ENABLED: true
  GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
  GF_USERS_DEFAULT_THEME: light
