---
apiVersion: microgateway.airlock.com/v1alpha1
kind: ContentSecurityPolicy
metadata:
  name: webserver
  namespace: oidc
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: webserver
  secured:
    headerRewritesRef:
      name: webserver
    filter:
      denyRulesRef:
        name: webserver
