---
apiVersion: microgateway.airlock.com/v1alpha1
kind: DenyRules
metadata:
  name: webserver
  namespace: airlock-gateway-auth
spec:
  request:
    builtIn:
      settings:
        level: Strict
        threatHandlingMode: LogOnly
