---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webserver-tls-cert
  namespace: airlock-gateway-auth
spec:
  secretName: webserver-tls-cert
  commonName: webserver-127-0-0-1.nip.io
  dnsNames:
  - webserver-127-0-0-1.nip.io
  issuerRef:
    name: cluster-ca-issuer
    kind: ClusterIssuer
  privateKey:
    size: 4096
  usages:
  - server auth
  - digital signature
