apiVersion: microgateway.airlock.com/v1alpha1
kind: GatewayParameters
metadata:
  name: gatewayparameters-auth
  namespace: airlock-gateway-auth
spec:
  logging:
    level: info
  kubernetes:
    service:
      type: LoadBalancer
      externalTrafficPolicy: Cluster
    deployment:
      replicas: 1
      placement: {}
      engineContainer: {}
      automountServiceAccountToken: false
  defaults:
    sessionHandlingRef:
      name: sessionagent
