---
apiVersion: microgateway.airlock.com/v1alpha1
kind: IdentityPropagation
metadata:
  name: webserver-email
  namespace: oidc
spec:
  header:
    name: X-USER-EMAIL
    value:
      source:
        oidc:
          idToken:
            claim: "email"
