apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-ca
  namespace: oidc
spec:
  secretName: web-ca
  duration: 87600h
  renewBefore: 720h
  isCA: false
  commonName: web-ca
  issuerRef:
    name: cluster-ca-issuer
    kind: ClusterIssuer
