---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- apache-html.yaml
- apache-tls-cert.yaml
- certificate-web-ca.yaml
- deployment.yaml
- service.yaml
- webserver-config.yaml
