---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: oidc
  labels:
    app.kubernetes.io/name: webserver
spec:
  selector:
    app.kubernetes.io/name: webserver
  ports:
  - name: http
    port: 8080
    protocol: TCP
  - name: https
    port: 8443
    protocol: TCP
