apiVersion: v1
kind: ConfigMap
metadata:
    name: webserver-config
    namespace: oidc
data:
    httpd.conf: |
        ServerRoot "/usr/local/apache2"
        Listen 8080
        Listen 8443

        # Load core modules
        # Load all required modules
        LoadModule mpm_event_module modules/mod_mpm_event.so
        LoadModule http2_module modules/mod_http2.so
        LoadModule dir_module modules/mod_dir.so
        LoadModule mime_module modules/mod_mime.so
        LoadModule authz_core_module modules/mod_authz_core.so
        LoadModule log_config_module modules/mod_log_config.so
        LoadModule alias_module modules/mod_alias.so
        LoadModule unixd_module modules/mod_unixd.so
        LoadModule ssl_module modules/mod_ssl.so

        ServerAdmin you@example.com
        ServerName webserver-127-0-0-1.nip.io

        LogLevel debug ssl:debug http2:debug


        Protocols h2c http/1.1

        DocumentRoot "/usr/local/apache2/htdocs"
        <Directory "/usr/local/apache2/htdocs">
            Options Indexes FollowSymLinks
            AllowOverride None
            Require all granted
        </Directory>

        # Logging
        LogFormat "{ \"timestamp\":\"%t\", \"remote_ip\":\"%a\", \"method\":\"%m\", \"request\":\"%U\", \"protocol\":\"%H\", \"status\":%>s, \"bytes\":%b }" json
        CustomLog /proc/self/fd/1 json
        ErrorLog /proc/self/fd/2

        # Aliases
        Alias /user /usr/local/apache2/htdocs/user.html
        Alias /admin /usr/local/apache2/htdocs/admin.html

        <Location />
            SetHandler default-handler
        </Location>

        <Location /user>
            SetHandler default-handler
        </Location>

        <Location /admin>
            SetHandler default-handler
        </Location>

        # SSL VirtualHost
        <VirtualHost _default_:8443>
            Protocols h2 http/1.1
            H2Direct on
            H2ModernTLSOnly on
            DocumentRoot "/usr/local/apache2/htdocs"
            SSLEngine on
            SSLCertificateFile /etc/apache2/certs/tls.crt
            SSLCertificateKeyFile /etc/apache2/certs/tls.key

            <Directory "/usr/local/apache2/htdocs">
                Options Indexes FollowSymLinks
                AllowOverride None
                Require all granted
            </Directory>

            LogFormat "{ \"timestamp\":\"%t\", \"remote_ip\":\"%a\", \"method\":\"%m\", \"request\":\"%U\", \"protocol\":\"%H\", \"status\":%>s, \"bytes\":%b }" json
            CustomLog /proc/self/fd/1 json
            ErrorLog /proc/self/fd/2
        </VirtualHost>
