apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-shop
  labels:
    app: juice-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juice-shop
  template:
    metadata:
      labels:
        app: juice-shop
    spec:
      volumes:
      - name: well-known-csaf
        emptyDir: {}
      initContainers:
      - name: init-csaf-dir
        image: busybox
        command: [ "/bin/sh", "-c" ]
        args:
        - mkdir -p /mnt/csaf && touch /mnt/csaf/provider-metadata.json
        volumeMounts:
        - name: well-known-csaf
          mountPath: /mnt/csaf
      containers:
      - name: juice-shop
        image: bkimminich/juice-shop:v18.0.0
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: well-known-csaf
          mountPath: /juice-shop/.well-known/csaf
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ "ALL" ]
