apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airlock-gateway-auth

resources:

- redis-password-secret.yaml
- redisprovider.yaml
- redis-client-cert.yaml
- sessionHandling.yaml
